### ISSUE TITLE
Unable to save the driver code.

### ISSUE THREAD

**Issue by thenamelessthing** [sburke781/AndroidTVNotify#1]
SI tried to add new device driver and I got the error  "unexpected char: '\' @ line 91, column 109. "  When I want to save the driver. For now I can't save...

![image](https://github.com/sburke781/AndroidTVNotify/assets/10235448/06edfc8a-c130-4228-9590-59f3508e3d30)

**Comment by thenamelessthing** [comment]
I ask to chatgpt where is the error and he suggest :

def bodyJson = "{\"duration\": \"${DisplayDuration}\", \"position\": ${Position}, \"title\": \"${title}\", \"titleColor\": \"${TitleColor}\", \"titleSize\": ${TitleSize}, \"message\": \"${text}\", \"messageColor\": \"${MessageColor}\", \"messageSize\": ${MessageSize}, \"backgroundColor\": \"${BackgroundColor}\", \"media\": {} }";

Now I can save.. I will do some test in the next few day. Stay tuned!

**Comment by sburke781** [comment]
That is where the error is, but the slashes in the bodyJSON string are required.  I missed one out at the end of the title value.  I'll update the code later this evening or you can update it on your hub if you want

**Comment by thenamelessthing** [comment]
I modified the code with the following:

 def bodyJson = "{\"duration\": \"${DisplayDuration}\", \"position\": ${Position}, \"title\": \"${title}\", \"titleColor\": \"${TitleColor}\", \"titleSize\": ${TitleSize}, \"message\": \"${text}\", \"messageColor\": \"${MessageColor}\", \"messageSize\": ${MessageSize}, \"backgroundColor\": \"${BackgroundColor}\", \"media\": {} }";
 
 
 But no change..

**Comment by sburke781** [comment]
Hi @thenamelessthing,

Unfortunately I think GitHub removes some of the slashes from the comments that (at least) I add.  This is the change I made to the code, adding the second backslash to the title value.  Can you please try the update driver code.  I still cannot guarantee it will work, but you should at least be able to save the driver.

![image](https://github.com/sburke781/AndroidTVNotify/assets/4384353/bd4a571e-9f70-48c2-9b68-c90234bd51e5)

**Comment by thenamelessthing** [comment]
Now I can save!
