### ISSUE TITLE
error when sending test notification error 400 bad request

### ISSUE THREAD

**Issue by thenamelessthing** [sburke781/AndroidTVNotify#2]
I created my virtual device with the new driver. 

![image](https://github.com/sburke781/AndroidTVNotify/assets/10235448/5f13947a-261e-40f6-89b6-d16a07d87afa)

I put the ip address of my shield TV and send test notification. But in hubitat log I got:

![image](https://github.com/sburke781/AndroidTVNotify/assets/10235448/319e58da-a4c8-4b23-9890-70bf788f4700)

I also installed on my Shield the PiPup app and I can confirm that  listening port on the shield is reachable.

**Comment by sburke781** [comment]
I expect this may be related to the other issue of the missing slash in the body.  Let's see what happens when that is fixed.

**Comment by thenamelessthing** [comment]
I tried with your correction without success. Same error. I also tried to enable debug in the virtual device but that doesn't show anything else..

**Comment by sburke781** [comment]
Hmm... Ok, thanks for trying... Let me test a few things myself.  It could be later in the week before I come back with something.

If you are keen.... My first thoughts are:

 + Set the colors to valid / default colors for PiPup, from the GitHub documentation for the PiPup App
 + Remove the media section from the bodyJSON string, i.e. the "media": { } (including the backslashes before the double-quotes

**Comment by thenamelessthing** [comment]
I set the color value and no luck.

![image](https://github.com/sburke781/AndroidTVNotify/assets/10235448/fcbc1861-07ac-41bb-97b5-0b0041cdb404)


Removed the media section and same thing..

![image](https://github.com/sburke781/AndroidTVNotify/assets/10235448/9570ea1d-c3ff-43ac-81e3-7d3b2e6a3c6d)

**Comment by sburke781** [comment]
@thenamelessthing - with the media removal, can you show the driver code below the comment section you showed in your screenshot?  Happy to provide an updated driver if it would make it easier.

**Comment by thenamelessthing** [comment]
Here the driver code

//Notification Methods
void deviceNotification(String text) {

  deviceNotification(text, DefaultTitle);
}

void deviceNotification(String text, String title) {

  def headers = [:];
  headers.put("Content-Type", "application/json");
  def bodyJson = "{\"duration\": \"${DisplayDuration}\", \"position\": ${Position}, \"title\": \"${title}\", \"titleColor\": \"${TitleColor}\", \"titleSize\": ${TitleSize}, \"message\": \"${text}\", \"messageColor\": \"${MessageColor}\", \"messageSize\": ${MessageSize}, \"backgroundColor\": \"${BackgroundColor}\", \"media\": {} }";
  def postParams = [
        uri: "http://${TVIPAddress}:7979/notify",
        headers: headers,
        contentType: 'application/json',
        body : bodyJson
	]


    try {
        
        httpPost(postParams)
        { resp -> 
            debugLog("deviceNotification: ${resp.data}")
            
        }
            
	}
	catch (Exception e) {
        errorLog("deviceNotification: Unable to send notification: ${e}")
	}
}


//Logging Utility methods

**Comment by sburke781** [comment]
This is the bit I want you to remove:

![image](https://github.com/sburke781/AndroidTVNotify/assets/4384353/f1db0ff2-8353-4ba7-90b3-67cad60418a8)

**Comment by thenamelessthing** [comment]
Some progress. A new error code!

![image](https://github.com/sburke781/AndroidTVNotify/assets/10235448/5255a62e-8e3b-4dcd-9632-9f186a073b33)

**Comment by sburke781** [comment]
That's odd, 200 and OK?  Did the notification display on the TV?  I'll check the driver code and apply the updates we have made so far.

**Comment by thenamelessthing** [comment]
Following the solution here: https://github.com/rogro82/PiPup/issues/45#issuecomment-1436107783

Now I see the notification!

**Comment by sburke781** [comment]
Excellent news.  Thanks for following that up @thenamelessthing .  I'll tidy up the driver ready for release.  Not sure when I will be able to finalise it, but hopeful of the next few weeks.

**Comment by thenamelessthing** [comment]
Can we look for the media part too?

**Comment by sburke781** [comment]
> Can we look for the media part too?

Yes, I have setup an issue to look at this. 

https://github.com/sburke781/AndroidTVNotify/issues/3

I am thinking now I will continue with rolling my version of the driver out, once I finish these last few items.
